services: 
  ms_server:
    container_name: ms_server  
    build: 
      context: ./calificaciones_service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=SECRET_MONGODB_URI
      - API_FRONT=http://localhost:3000
    command:  npm run start
  
  ms_client:
    container_name: ms_client
    build: 
      context: ./fb_web_service
    ports:
      - "3000:80"
  
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: ./reverse_proxy 
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx
